[package]
name = "copp"
version = "0.2.0"
edition = "2024"
rust-version = "1.88"
description = "Convex-objective path parameterization for robotic trajectory planning."
license = "MIT"
readme = "README.md"
repository = "https://github.com/TOPP-THU/copp"
categories = ["science::robotics", "algorithms", "mathematics", "simulation"]
keywords = [
    "trajectory-planning",
    "jerk-limited",
    "motion-planning",
    "convex-optimization",
    "time-optimal",
]
exclude = ["data/**", "target/**"]

[lib]
name = "copp"
crate-type = ["rlib", "cdylib", "staticlib"]


[dependencies]
nalgebra = "0.34.1"
clarabel = "0.11.1"
thiserror = "2.0.18"
itertools = "0.14.0"
chrono = "0.4.44"
rayon = "1.10.0"
log = "0.4.28"

[dev-dependencies]
rand = "0.10.1"
plotters = "0.3.7"
env_logger = "0.11.8"

# Only use for the final release.
# [profile.release]
# opt-level = 3
# codegen-units = 1
# lto = "fat"

# [[bench]]

[package.metadata.docs.rs]
# The following line adds MathJax support for rendering mathematical equations in documentation.
# Run `cargo doc` to generate the documentation with MathJax.
rustdoc-args = ["--html-in-header", "mathjax-config.html"]
