#ifndef COPP_COPP2_H
#define COPP_COPP2_H

/*
 * Generated by bindings/c/scripts/generate_headers.ps1.
 * Do not edit by hand; update src/ffi/c and regenerate.
 */

/**
 * \file copp2.h
 * \brief COPP2-SOCP solver APIs.
 * \ingroup copp_copp2
 */

#include <stddef.h>
#include <stdbool.h>
#include <stdint.h>
#include "copp/core.h"
#include "copp/formulation.h"

#ifdef __cplusplus
extern "C" {
#endif

/**
 * \addtogroup copp_copp2
 * @{
 */

/**
 * Compact COPP2-SOCP expert result returned to C.
 *
 * `has_a` is true only when the Clarabel status is accepted by
 * `CoppClarabelOptions`. When true, `a` owns a COPP-allocated vector and the
 * whole result must be released with `copp2_socp_result_free`. When false,
 * `a` is empty and diagnostics still describe the Clarabel run.
 */
typedef struct Copp2SocpResult {
    /**
     * Whether `a` contains an accepted `a(s) = (ds/dt)^2` profile.
     */
    bool has_a;
    /**
     * Accepted `a` profile, or an empty vector when `has_a == false`.
     */
    struct CoppVecF64 a;
    /**
     * Raw Clarabel primal solution vector.
     */
    struct CoppVecF64 x;
    /**
     * Raw Clarabel dual solution vector.
     */
    struct CoppVecF64 z;
    /**
     * Raw Clarabel primal-cone slack vector.
     */
    struct CoppVecF64 s;
    /**
     * Final Clarabel solver status.
     */
    enum CoppClarabelSolverStatus solver_status;
    /**
     * Primal objective value reported by Clarabel.
     */
    double obj_val;
    /**
     * Dual objective value reported by Clarabel.
     */
    double obj_val_dual;
    /**
     * Clarabel solve time in seconds.
     */
    double solve_time;
    /**
     * Number of interior-point iterations.
     */
    uint32_t iterations;
    /**
     * Primal residual reported by Clarabel.
     */
    double r_prim;
    /**
     * Dual residual reported by Clarabel.
     */
    double r_dual;
    /**
     * Linear solver metadata reported by Clarabel.
     */
    struct CoppClarabelLinearSolverInfo linsolver;
    /**
     * Weighted COPP objective value computed from accepted `a`; NaN otherwise.
     */
    double objective_value;
    /**
     * Per-objective unweighted values computed from accepted `a`.
     */
    struct CoppVecF64 objective_terms;
} Copp2SocpResult;

/**
 * Solve a COPP2-SOCP problem.
 *
 * This C ABI builds an internal COPP2 problem from the borrowed `Copp2Problem`,
 * forwards `options` to the Clarabel backend, and returns only the optimized
 * `a(s) = (ds/dt)^2` profile.
 *
 * Supported objective kinds are `Time`, `Linear`, `ThermalEnergy`, and
 * `TotalVariationTorque`.  The torque objectives use the robot's stored
 * inverse-dynamics callback when provided, otherwise point dynamics
 * (`tau = ddq`) is used.
 *
 * On success, `out_a` owns a COPP-allocated vector over the closed station
 * interval and must be released with `copp_vec_f64_free`.
 *
 * \warning Safety
 * `problem.robot` must be a non-null handle returned by `copp_robot_create`
 * and must remain valid for the duration of this call. `problem.objectives`
 * must be valid for `problem.num_objectives` reads when
 * `problem.num_objectives` is non-zero. If the robot has a stored
 * inverse-dynamics callback, it must remain valid for this call. The robot
 * must not be freed or mutated concurrently during the solve. `out_a` must
 * be valid for one `CoppVecF64` write.
 */
enum CoppStatus copp2_socp(struct Copp2Problem problem,
                           struct CoppClarabelOptions options,
                           struct CoppVecF64 *out_a);

/**
 * Solve a COPP2-SOCP problem and always return Clarabel diagnostics.
 *
 * This expert entry mirrors `copp2_socp_expert`: true runtime failures
 * still return a non-OK `CoppStatus`, but non-accepted Clarabel statuses are
 * reported inside `out_result` with `has_a == false` and the function returns
 * `COPP_STATUS_OK`.
 *
 * \warning Safety
 * Same safety requirements as `copp2_socp`. `out_result` must be valid for
 * one `Copp2SocpResult` write and must later be released with
 * `copp2_socp_result_free`.
 */
enum CoppStatus copp2_socp_expert(struct Copp2Problem problem,
                                  struct CoppClarabelOptions options,
                                  struct Copp2SocpResult *out_result);

/**
 * Release memory owned by a `Copp2SocpResult`.
 *
 * Passing an already-freed result is invalid. Prefer freeing the full result
 * with this function instead of freeing `result.a` manually.
 */
void copp2_socp_result_free(struct Copp2SocpResult result);

/** @} */

#ifdef __cplusplus
}
#endif

#endif /* COPP_COPP2_H */
