#ifndef COPP_H
#define COPP_H

/*
 * Generated by bindings/c/scripts/generate_headers.ps1.
 * Do not edit by hand; update src/ffi/c and regenerate.
 */

/*
 * COPP C ABI umbrella header.
 *
 * Include this file for the full C ABI surface, or include a narrower header
 * such as "copp/path.h" or "copp/topp2.h" for smaller translation
 * units.
 */

#include "copp/core.h"
#include "copp/path.h"
#include "copp/robot.h"
#include "copp/formulation.h"
#include "copp/interpolation.h"
#include "copp/topp2.h"
#include "copp/copp2.h"
#include "copp/topp3.h"
#include "copp/copp3.h"

#endif /* COPP_H */
