#ifndef COPP_COPP3_H
#define COPP_COPP3_H

/*
 * Generated by bindings/c/scripts/generate_headers.ps1.
 * Do not edit by hand; update src/ffi/c and regenerate.
 */

/**
 * \file copp3.h
 * \brief COPP3-SOCP solver APIs.
 * \ingroup copp_copp3
 */

#include <stddef.h>
#include <stdbool.h>
#include <stdint.h>
#include "copp/core.h"
#include "copp/formulation.h"
#include "copp/topp3.h"

#ifdef __cplusplus
extern "C" {
#endif

/**
 * \addtogroup copp_copp3
 * @{
 */

/**
 * Compact COPP3-SOCP expert result returned to C.
 *
 * `has_profile` is true only when the Clarabel status is accepted by
 * `CoppClarabelOptions`. When true, `profile` owns COPP-allocated `a` and `b`
 * vectors and the whole result must be released with
 * `copp3_socp_result_free`. When false, `profile` is empty and diagnostics
 * still describe the Clarabel run.
 */
typedef struct Copp3SocpResult {
    /**
     * Whether `profile` contains an accepted third-order profile.
     */
    bool has_profile;
    /**
     * Accepted third-order profile, or an empty profile when
     * `has_profile == false`.
     */
    struct CoppProfile3rd profile;
    /**
     * Raw Clarabel primal solution vector.
     */
    struct CoppVecF64 x;
    /**
     * Raw Clarabel dual solution vector.
     */
    struct CoppVecF64 z;
    /**
     * Raw Clarabel primal-cone slack vector.
     */
    struct CoppVecF64 s;
    /**
     * Final Clarabel solver status.
     */
    enum CoppClarabelSolverStatus solver_status;
    /**
     * Primal objective value reported by Clarabel.
     */
    double obj_val;
    /**
     * Dual objective value reported by Clarabel.
     */
    double obj_val_dual;
    /**
     * Clarabel solve time in seconds.
     */
    double solve_time;
    /**
     * Number of interior-point iterations.
     */
    uint32_t iterations;
    /**
     * Primal residual reported by Clarabel.
     */
    double r_prim;
    /**
     * Dual residual reported by Clarabel.
     */
    double r_dual;
    /**
     * Linear solver metadata reported by Clarabel.
     */
    struct CoppClarabelLinearSolverInfo linsolver;
    /**
     * Weighted COPP objective value computed from accepted profile; NaN
     * otherwise.
     */
    double objective_value;
    /**
     * Per-objective unweighted values computed from accepted profile.
     */
    struct CoppVecF64 objective_terms;
} Copp3SocpResult;

/**
 * Solve a COPP3-SOCP problem.
 *
 * This C ABI builds an internal COPP3 problem from the borrowed `Copp3Problem`,
 * forwards `options` to the Clarabel backend, and returns only the accepted
 * third-order profile.
 *
 * Supported objective kinds are `Time`, `Linear`, `ThermalEnergy`, and
 * `TotalVariationTorque`. Torque objectives use the robot's stored
 * inverse-dynamics callback when provided, otherwise point dynamics
 * (`tau = ddq`) is used.
 *
 * On success, `out_profile` owns COPP-allocated `a` and `b` vectors and must
 * be released with `copp_profile_3rd_free`.
 *
 * \warning Safety
 * `problem.robot` must be a non-null mutable handle returned by
 * `copp_robot_create` and must remain valid for the duration of this call.
 * `problem.objectives` must be valid for `problem.num_objectives` reads when
 * non-zero. If the robot has a stored inverse-dynamics callback, it must
 * remain valid for this call. The solver builds the internal problem by
 * linearizing third-order constraints, which mutates the robot's internal
 * constraint cache. `out_profile` must be valid for one `CoppProfile3rd`
 * write.
 */
enum CoppStatus copp3_socp(struct Copp3Problem problem,
                           struct CoppClarabelOptions options,
                           struct CoppProfile3rd *out_profile);

/**
 * Solve a COPP3-SOCP problem and always return Clarabel diagnostics.
 *
 * This expert entry mirrors `copp3_socp_expert`: true runtime failures
 * still return a non-OK `CoppStatus`, but non-accepted Clarabel statuses are
 * reported inside `out_result` with `has_profile == false` and the function
 * returns `COPP_STATUS_OK`.
 *
 * \warning Safety
 * Same safety requirements as `copp3_socp`. `out_result` must be valid for
 * one `Copp3SocpResult` write and must later be released with
 * `copp3_socp_result_free`.
 */
enum CoppStatus copp3_socp_expert(struct Copp3Problem problem,
                                  struct CoppClarabelOptions options,
                                  struct Copp3SocpResult *out_result);

/**
 * Release memory owned by a `Copp3SocpResult`.
 *
 * Passing an already-freed result is invalid. Prefer freeing the full result
 * with this function instead of freeing `result.profile` manually.
 */
void copp3_socp_result_free(struct Copp3SocpResult result);

/** @} */

#ifdef __cplusplus
}
#endif

#endif /* COPP_COPP3_H */
