#ifndef COPP_CORE_H
#define COPP_CORE_H

/*
 * Generated by bindings/c/scripts/generate_headers.ps1.
 * Do not edit by hand; update src/ffi/c and regenerate.
 */

/**
 * \file core.h
 * \brief Core status, memory, matrix, and shared solver option types.
 * \ingroup copp_core
 */

#include <stddef.h>
#include <stdbool.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * \addtogroup copp_core
 * @{
 */

/**
 * C ABI status code returned by COPP FFI functions.
 *
 * The numeric ranges are grouped by subsystem so future bindings can preserve
 * source compatibility while still reporting precise failure classes.
 */
typedef enum CoppStatus {
    /**
     * Operation completed successfully.
     */
    COPP_STATUS_OK = 0,
    /**
     * A required pointer argument was null.
     */
    COPP_STATUS_NULL_POINTER = 1,
    /**
     * A slice length or vector length was invalid.
     */
    COPP_STATUS_INVALID_LENGTH = 2,
    /**
     * A matrix/vector shape was invalid.
     */
    COPP_STATUS_INVALID_SHAPE = 3,
    /**
     * An unsupported enum value or option was provided through the C ABI.
     */
    COPP_STATUS_INVALID_ARGUMENT = 4,
    /**
     * COPP caught an internal panic at the C ABI boundary.
     */
    COPP_STATUS_PANIC = 5,
    /**
     * A memory allocation failed or an output buffer could not be created.
     */
    COPP_STATUS_ALLOCATION_FAILED = 6,
    /**
     * Filesystem or OS I/O failure.
     */
    COPP_STATUS_IO_ERROR = 100,
    /**
     * Constraint input `s` is not strictly increasing.
     */
    COPP_STATUS_CONSTRAINT_NON_INCREASING_S = 200,
    /**
     * Constraint input dimensions do not match the expected shape.
     */
    COPP_STATUS_CONSTRAINT_NO_MATCH_DIMENSIONS = 201,
    /**
     * Constraint input ordering does not match the expected contract.
     */
    COPP_STATUS_CONSTRAINT_NO_MATCH_ORDER = 202,
    /**
     * Signed upper/lower bounds do not satisfy strict feasibility rules.
     */
    COPP_STATUS_CONSTRAINT_INVALID_SIGNED_BOUNDS = 203,
    /**
     * Requested station interval is outside the stored constraint range.
     */
    COPP_STATUS_CONSTRAINT_OUT_OF_S_BOUNDS = 204,
    /**
     * Profile `a` violates positivity requirements.
     */
    COPP_STATUS_CONSTRAINT_NON_POSITIVE_A = 205,
    /**
     * Linearization floor is not strictly positive.
     */
    COPP_STATUS_CONSTRAINT_NON_POSITIVE_LINEARIZATION_FLOOR = 206,
    /**
     * Required path derivative data is missing.
     */
    COPP_STATUS_CONSTRAINT_NO_GIVEN_Q_INFO = 207,
    /**
     * Linearized jerk constraints are unavailable for the requested station.
     */
    COPP_STATUS_CONSTRAINT_LINEAR_JERK_NOT_AVAILABLE = 208,
    /**
     * Required dynamic-model data is unavailable.
     */
    COPP_STATUS_CONSTRAINT_NO_DYNAMIC = 209,
    /**
     * Reference profile is infeasible under current constraints.
     */
    COPP_STATUS_CONSTRAINT_INFEASIBLE_REFERENCE = 210,
    /**
     * Requested constraint interval is empty.
     */
    COPP_STATUS_CONSTRAINT_EMPTY_INTERVAL = 211,
    /**
     * Path dimension is invalid.
     */
    COPP_STATUS_PATH_INVALID_DIMENSION = 300,
    /**
     * Path parameter range is invalid.
     */
    COPP_STATUS_PATH_INVALID_RANGE = 301,
    /**
     * Spline order is invalid.
     */
    COPP_STATUS_PATH_INVALID_ORDER = 302,
    /**
     * Path matrix/tensor dimensions are incompatible.
     */
    COPP_STATUS_PATH_DIMENSION_MISMATCH = 303,
    /**
     * Not enough waypoints were supplied to build a path.
     */
    COPP_STATUS_PATH_NOT_ENOUGH_WAYPOINTS = 304,
    /**
     * Query parameter is outside the configured path range.
     */
    COPP_STATUS_PATH_OUT_OF_RANGE_S = 305,
    /**
     * Requested spline boundary condition is unsupported.
     */
    COPP_STATUS_PATH_UNSUPPORTED_BOUNDARY = 306,
    /**
     * Internal spline/path linear system is singular.
     */
    COPP_STATUS_PATH_SINGULAR_SYSTEM = 307,
    /**
     * Requested path derivative order is not supported by this path.
     */
    COPP_STATUS_PATH_UNSUPPORTED_DERIVATIVE_ORDER = 308,
    /**
     * Solver reported infeasibility.
     */
    COPP_STATUS_SOLVER_INFEASIBLE = 400,
    /**
     * Solver reported unboundedness.
     */
    COPP_STATUS_SOLVER_UNBOUNDED = 401,
    /**
     * Solver rejected the input model or data.
     */
    COPP_STATUS_SOLVER_INVALID_INPUT = 402,
    /**
     * Solver rejected the provided options.
     */
    COPP_STATUS_SOLVER_INVALID_OPTIONS = 403,
    /**
     * Clarabel returned an internal solver error.
     */
    COPP_STATUS_CLARABEL_SOLVER_ERROR = 404,
    /**
     * Clarabel terminated with a non-success status.
     */
    COPP_STATUS_CLARABEL_SOLVER_STATUS = 405,
    /**
     * Backend-specific or uncategorized solver/runtime error.
     */
    COPP_STATUS_SOLVER_OTHER = 499,
    /**
     * User-provided robot inverse dynamics failed.
     */
    COPP_STATUS_ROBOT_DYNAMICS_ERROR = 500,
} CoppStatus;

/**
 * Return a short static message for a COPP status code.
 *
 * The returned pointer is a static null-terminated string owned by the library.
 */
const char *copp_status_message(enum CoppStatus status);

/**
 * Return the status code associated with the current thread's last error.
 *
 * A successful COPP C ABI call clears this slot back to `COPP_STATUS_OK`.
 */
enum CoppStatus copp_last_error_code(void);

/**
 * Return the current thread's last detailed error message as UTF-8.
 *
 * The returned pointer is owned by COPP and remains valid until the next COPP
 * C ABI call on the same thread updates or clears the last-error slot.
 * When no error is stored, this returns an empty string.
 */
const char *copp_last_error_message(void);

/**
 * Return the length in bytes of the current thread's last UTF-8 error message.
 *
 * The terminating null byte is not included in the returned length.
 */
size_t copp_last_error_message_len(void);

/**
 * Copy the current thread's last UTF-8 error message into a caller buffer.
 *
 * `out_len`, when non-null, receives the full message length in bytes,
 * excluding the terminating null byte, even when `capacity` is too small.
 * If `buffer` is non-null and `capacity > 0`, COPP always writes a
 * null-terminated, possibly truncated UTF-8 prefix.
 *
 * \warning Safety
 * `buffer` must be valid for `capacity` writable bytes when `capacity > 0`.
 * `out_len`, when non-null, must be valid for one `size_t` write.
 */
enum CoppStatus copp_last_error_message_copy(char *buffer, size_t capacity, size_t *out_len);

/**
 * Clear the current thread's last detailed error message.
 */
void copp_clear_last_error(void);

/**
 * Set the current thread's last detailed error message from a C string.
 *
 * The message is interpreted as UTF-8 with lossy replacement for invalid byte
 * sequences. Interior null bytes cannot appear in this C-string variant; use
 * `copp_set_last_error_message_n` when the message length is known.
 *
 * \warning Safety
 * `message` must point to a null-terminated byte string when non-null.
 */
enum CoppStatus copp_set_last_error_message(enum CoppStatus status, const char *message);

/**
 * Set the current thread's last detailed error message from a byte slice.
 *
 * The message is interpreted as UTF-8 with lossy replacement for invalid byte
 * sequences, interior null bytes are replaced, and the stored message is
 * capped at 64 KiB.
 *
 * \warning Safety
 * `message` must be valid for `len` reads when `len > 0`.
 */
enum CoppStatus copp_set_last_error_message_n(enum CoppStatus status,
                                              const char *message,
                                              size_t len);

/**
 * Return the COPP library version.
 *
 * The returned pointer is a static null-terminated string owned by the library.
 */
const char *copp_version(void);

/**
 * C ABI verbosity level for solver diagnostics.
 */
typedef enum CoppVerbosity {
    /**
     * No log will be emitted.
     */
    COPP_VERBOSITY_SILENT = 0,
    /**
     * Only summary information will be emitted.
     */
    COPP_VERBOSITY_SUMMARY = 1,
    /**
     * Detailed debug information will be emitted.
     */
    COPP_VERBOSITY_DEBUG = 2,
    /**
     * Very detailed trace information will be emitted.
     */
    COPP_VERBOSITY_TRACE = 3,
} CoppVerbosity;

/**
 * Direct linear solver method forwarded to Clarabel.
 */
typedef enum CoppClarabelDirectSolveMethod {
    /**
     * Let Clarabel choose the direct solver.
     */
    COPP_CLARABEL_DIRECT_SOLVE_METHOD_AUTO = 0,
    /**
     * Use Clarabel's QDLDL backend.
     */
    COPP_CLARABEL_DIRECT_SOLVE_METHOD_QDLDL = 1,
    /**
     * Use the optional FAER sparse backend when compiled into Clarabel.
     */
    COPP_CLARABEL_DIRECT_SOLVE_METHOD_FAER = 2,
    /**
     * Use the optional MKL Pardiso backend when compiled into Clarabel.
     */
    COPP_CLARABEL_DIRECT_SOLVE_METHOD_MKL = 3,
    /**
     * Use the optional Panua Pardiso backend when compiled into Clarabel.
     */
    COPP_CLARABEL_DIRECT_SOLVE_METHOD_PANUA = 4,
} CoppClarabelDirectSolveMethod;

/**
 * Clarabel solver status returned by SOCP expert results.
 */
typedef enum CoppClarabelSolverStatus {
    /**
     * Solver has not run.
     */
    COPP_CLARABEL_SOLVER_STATUS_UNSOLVED = 0,
    /**
     * Solver terminated with a solution.
     */
    COPP_CLARABEL_SOLVER_STATUS_SOLVED = 1,
    /**
     * Problem is primal infeasible.
     */
    COPP_CLARABEL_SOLVER_STATUS_PRIMAL_INFEASIBLE = 2,
    /**
     * Problem is dual infeasible.
     */
    COPP_CLARABEL_SOLVER_STATUS_DUAL_INFEASIBLE = 3,
    /**
     * Solver terminated with a reduced-accuracy solution.
     */
    COPP_CLARABEL_SOLVER_STATUS_ALMOST_SOLVED = 4,
    /**
     * Problem is primal infeasible with reduced accuracy.
     */
    COPP_CLARABEL_SOLVER_STATUS_ALMOST_PRIMAL_INFEASIBLE = 5,
    /**
     * Problem is dual infeasible with reduced accuracy.
     */
    COPP_CLARABEL_SOLVER_STATUS_ALMOST_DUAL_INFEASIBLE = 6,
    /**
     * Iteration limit reached before an accepted solution or certificate.
     */
    COPP_CLARABEL_SOLVER_STATUS_MAX_ITERATIONS = 7,
    /**
     * Time limit reached before an accepted solution or certificate.
     */
    COPP_CLARABEL_SOLVER_STATUS_MAX_TIME = 8,
    /**
     * Solver terminated with a numerical error.
     */
    COPP_CLARABEL_SOLVER_STATUS_NUMERICAL_ERROR = 9,
    /**
     * Solver terminated due to lack of progress.
     */
    COPP_CLARABEL_SOLVER_STATUS_INSUFFICIENT_PROGRESS = 10,
    /**
     * Solver terminated by callback.
     */
    COPP_CLARABEL_SOLVER_STATUS_CALLBACK_TERMINATED = 11,
} CoppClarabelSolverStatus;

/**
 * Linear solver metadata reported by Clarabel.
 */
typedef struct CoppClarabelLinearSolverInfo {
    /**
     * Linear solver method name mapped to COPP's stable enum.
     */
    enum CoppClarabelDirectSolveMethod method;
    /**
     * Number of threads used by the linear solver.
     */
    size_t threads;
    /**
     * Whether the linear solver used a direct factorization method.
     */
    bool direct;
    /**
     * Number of nonzeros in the linear system.
     */
    size_t nnz_a;
    /**
     * Number of nonzeros in the factored system.
     */
    size_t nnz_l;
} CoppClarabelLinearSolverInfo;

/**
 * Advanced raw Clarabel solver settings.
 *
 * This mirrors the `clarabel::solver::DefaultSettings<f64>` fields available
 * in the current build. Optional Clarabel backends, such as FAER or Pardiso,
 * are selected through `direct_solve_method`; if the linked Clarabel was not
 * compiled with that backend, the solve returns a solver/options error.
 */
typedef struct CoppClarabelSettings {
    /**
     * Maximum number of interior-point iterations.
     */
    uint32_t max_iter;
    /**
     * Maximum solve time in seconds.
     */
    double time_limit;
    /**
     * Enable Clarabel's internal solver log.
     */
    bool verbose;
    /**
     * Maximum interior-point step length.
     */
    double max_step_fraction;
    /**
     * Absolute duality-gap tolerance.
     */
    double tol_gap_abs;
    /**
     * Relative duality-gap tolerance.
     */
    double tol_gap_rel;
    /**
     * Primal/dual feasibility tolerance.
     */
    double tol_feas;
    /**
     * Absolute infeasibility tolerance.
     */
    double tol_infeas_abs;
    /**
     * Relative infeasibility tolerance.
     */
    double tol_infeas_rel;
    /**
     * Kappa/tau tolerance.
     */
    double tol_ktratio;
    /**
     * Reduced absolute duality-gap tolerance for almost-solved status.
     */
    double reduced_tol_gap_abs;
    /**
     * Reduced relative duality-gap tolerance for almost-solved status.
     */
    double reduced_tol_gap_rel;
    /**
     * Reduced feasibility tolerance for almost-solved status.
     */
    double reduced_tol_feas;
    /**
     * Reduced absolute infeasibility tolerance for almost-solved status.
     */
    double reduced_tol_infeas_abs;
    /**
     * Reduced relative infeasibility tolerance for almost-solved status.
     */
    double reduced_tol_infeas_rel;
    /**
     * Reduced kappa/tau tolerance for almost-solved status.
     */
    double reduced_tol_ktratio;
    /**
     * Enable data equilibration before solving.
     */
    bool equilibrate_enable;
    /**
     * Maximum number of equilibration iterations.
     */
    uint32_t equilibrate_max_iter;
    /**
     * Minimum equilibration scaling.
     */
    double equilibrate_min_scaling;
    /**
     * Maximum equilibration scaling.
     */
    double equilibrate_max_scaling;
    /**
     * Backtracking factor used by the line search.
     */
    double linesearch_backtrack_step;
    /**
     * Minimum step length for asymmetric-cone switching.
     */
    double min_switch_step_length;
    /**
     * Minimum step length for termination checks.
     */
    double min_terminate_step_length;
    /**
     * Maximum solver threads. `0` lets Clarabel choose.
     */
    uint32_t max_threads;
    /**
     * Whether to use a direct KKT solver. Clarabel currently requires `true`.
     */
    bool direct_kkt_solver;
    /**
     * Direct linear solver method.
     */
    enum CoppClarabelDirectSolveMethod direct_solve_method;
    /**
     * Enable static KKT regularization.
     */
    bool static_regularization_enable;
    /**
     * Static KKT regularization constant.
     */
    double static_regularization_constant;
    /**
     * Static KKT regularization proportional term.
     */
    double static_regularization_proportional;
    /**
     * Enable dynamic KKT regularization.
     */
    bool dynamic_regularization_enable;
    /**
     * Dynamic regularization threshold.
     */
    double dynamic_regularization_eps;
    /**
     * Dynamic regularization shift.
     */
    double dynamic_regularization_delta;
    /**
     * Enable iterative refinement for direct solves.
     */
    bool iterative_refinement_enable;
    /**
     * Iterative-refinement relative tolerance.
     */
    double iterative_refinement_reltol;
    /**
     * Iterative-refinement absolute tolerance.
     */
    double iterative_refinement_abstol;
    /**
     * Iterative-refinement maximum iterations.
     */
    uint32_t iterative_refinement_max_iter;
    /**
     * Iterative-refinement stalling ratio.
     */
    double iterative_refinement_stop_ratio;
    /**
     * Enable Clarabel presolve.
     */
    bool presolve_enable;
    /**
     * Drop structural zeros from sparse inputs before solving.
     */
    bool input_sparse_dropzeros;
} CoppClarabelSettings;

/**
 * Shared Clarabel options for COPP SOCP solvers.
 */
typedef struct CoppClarabelOptions {
    /**
     * Crate-level verbosity for COPP assembly diagnostics.
     */
    enum CoppVerbosity verbosity;
    /**
     * Accept Clarabel status `AlmostSolved` as usable.
     */
    bool allow_almost_solved;
    /**
     * Accept Clarabel status `MaxIterations` as usable.
     */
    bool allow_max_iterations;
    /**
     * Accept Clarabel status `MaxTime` as usable.
     */
    bool allow_max_time;
    /**
     * Accept Clarabel status `CallbackTerminated` as usable.
     */
    bool allow_callback_terminated;
    /**
     * Accept Clarabel status `InsufficientProgress` as usable.
     */
    bool allow_insufficient_progress;
    /**
     * Advanced raw Clarabel solver settings.
     */
    struct CoppClarabelSettings clarabel_settings;
} CoppClarabelOptions;

/**
 * Write default shared Clarabel options into `out_options`.
 *
 * Defaults use COPP's default Clarabel settings and accept `Solved` and
 * `AlmostSolved` statuses.
 *
 * \warning Safety
 * `out_options` must be valid for one `CoppClarabelOptions` write.
 */
enum CoppStatus copp_clarabel_default_options(struct CoppClarabelOptions *out_options);

/**
 * Matrix memory layout used by `CoppMatrixViewF64`.
 *
 * COPP recommends column-major input because it matches nalgebra. Strictly
 * contiguous column-major input (`leading_dim == rows`) can be borrowed as a
 * slice, and padded column-major input (`leading_dim >= rows`) can be borrowed
 * as a strided matrix view. Row-major input is accepted, but COPP copies it
 * into column-major storage before passing it to COPP internals.
 */
typedef enum CoppMatrixLayout {
    /**
     * Column-major storage: element `(row, col)` is at
     * `data[row + col * leading_dim]`.
     */
    COPP_MATRIX_LAYOUT_COLUMN_MAJOR = 0,
    /**
     * Row-major storage: element `(row, col)` is at
     * `data[col + row * leading_dim]`.
     */
    COPP_MATRIX_LAYOUT_ROW_MAJOR = 1,
} CoppMatrixLayout;

/**
 * Borrowed immutable `f64` matrix passed from C to COPP.
 *
 * The matrix has shape `(rows, cols)` and uses the indexing rule selected by
 * `layout`. For contiguous column-major input, use `leading_dim = rows`. For
 * contiguous row-major input, use `leading_dim = cols`.
 *
 * Column-major input with `leading_dim >= rows` is the zero-copy path for
 * matrix-view consumers. Strictly contiguous column-major input with
 * `leading_dim == rows` is also accepted by APIs that require a raw
 * contiguous slice. Row-major input is copied once into column-major
 * temporary storage before COPP uses it.
 *
 * The pointer must reference enough initialized `double` values for the
 * selected layout unless `rows == 0` or `cols == 0`, in which case `data` may
 * be null. Borrowed matrix inputs must remain valid and must not be mutated
 * concurrently for the duration of the call.
 */
typedef struct CoppMatrixViewF64 {
    /**
     * Pointer to the first matrix element.
     */
    const double *data;
    /**
     * Number of matrix rows.
     */
    size_t rows;
    /**
     * Number of matrix columns.
     */
    size_t cols;
    /**
     * Matrix memory layout.
     */
    enum CoppMatrixLayout layout;
    /**
     * Leading dimension / physical stride.
     *
     * For column-major input this is the distance between consecutive
     * columns, and must be at least `rows` for non-empty matrices.
     * For row-major input this is the distance between consecutive rows, and
     * must be at least `cols` for non-empty matrices.
     */
    size_t leading_dim;
} CoppMatrixViewF64;

/**
 * Build a contiguous column-major matrix view.
 *
 * This is the recommended zero-copy input layout for COPP C APIs.
 */
#ifdef __cplusplus
#define COPP_MATRIX_VIEW_F64_COLUMN_MAJOR(data_, rows_, cols_) \
    CoppMatrixViewF64{(data_), (rows_), (cols_), COPP_MATRIX_LAYOUT_COLUMN_MAJOR, (rows_)}
#else
#define COPP_MATRIX_VIEW_F64_COLUMN_MAJOR(data_, rows_, cols_) \
    ((struct CoppMatrixViewF64){(data_), (rows_), (cols_), COPP_MATRIX_LAYOUT_COLUMN_MAJOR, (rows_)})
#endif

/**
 * Build a contiguous row-major matrix view.
 *
 * COPP accepts this layout, but it converts the input to column-major temporary
 * storage before use.
 */
#ifdef __cplusplus
#define COPP_MATRIX_VIEW_F64_ROW_MAJOR(data_, rows_, cols_) \
    CoppMatrixViewF64{(data_), (rows_), (cols_), COPP_MATRIX_LAYOUT_ROW_MAJOR, (cols_)}
#else
#define COPP_MATRIX_VIEW_F64_ROW_MAJOR(data_, rows_, cols_) \
    ((struct CoppMatrixViewF64){(data_), (rows_), (cols_), COPP_MATRIX_LAYOUT_ROW_MAJOR, (cols_)})
#endif

/**
 * Borrowed immutable `f64` slice passed from C to COPP.
 *
 * The pointer must reference at least `len` contiguous `double` values unless
 * `len == 0`, in which case `data` may be null.
 */
typedef struct CoppSliceF64 {
    /**
     * Pointer to the first element.
     */
    const double *data;
    /**
     * Number of elements.
     */
    size_t len;
} CoppSliceF64;

/**
 * Borrowed mutable `f64` slice passed from C to COPP.
 *
 * The pointer must reference at least `len` contiguous initialized `double`
 * values unless `len == 0`, in which case `data` may be null. Functions that
 * accept this type may modify the pointed-to values in place.
 */
typedef struct CoppSliceMutF64 {
    /**
     * Pointer to the first mutable element.
     */
    double *data;
    /**
     * Number of elements.
     */
    size_t len;
} CoppSliceMutF64;

/**
 * Library-owned `f64` vector returned to C.
 *
 * C callers may read `data[0..len]` and must release the vector exactly once
 * with `copp_vec_f64_free`.
 */
typedef struct CoppVecF64 {
    /**
     * Pointer to the first element, or null for an empty vector.
     */
    double *data;
    /**
     * Number of initialized elements.
     */
    size_t len;
    /**
     * Allocation capacity, used only by `copp_vec_f64_free`.
     */
    size_t capacity;
} CoppVecF64;

/**
 * Library-owned `usize` vector returned to C.
 *
 * C callers may read `data[0..len]` and must release the vector exactly once
 * with `copp_vec_usize_free`.
 */
typedef struct CoppVecUsize {
    /**
     * Pointer to the first element, or null for an empty vector.
     */
    size_t *data;
    /**
     * Number of initialized elements.
     */
    size_t len;
    /**
     * Allocation capacity, used only by `copp_vec_usize_free`.
     */
    size_t capacity;
} CoppVecUsize;

/**
 * Library-owned column-major `f64` matrix returned to C.
 *
 * C callers may read `data[0..rows * cols]` using column-major indexing and
 * must release the matrix exactly once with `copp_matrix_f64_free`.
 */
typedef struct CoppMatrixF64 {
    /**
     * Pointer to the first column-major element, or null for an empty matrix.
     */
    double *data;
    /**
     * Number of matrix rows.
     */
    size_t rows;
    /**
     * Number of matrix columns.
     */
    size_t cols;
    /**
     * Allocation capacity in number of `double` elements, used only by
     * `copp_matrix_f64_free`.
     */
    size_t capacity;
} CoppMatrixF64;

/**
 * Release a library-owned `f64` vector returned by COPP.
 *
 * \warning Safety
 * `vec` must either be empty/null or have been returned by a COPP C ABI
 * function. Passing arbitrary pointers or modified capacity fields is invalid.
 */
void copp_vec_f64_free(struct CoppVecF64 vec);

/**
 * Release a library-owned `usize` vector returned by COPP.
 *
 * \warning Safety
 * `vec` must either be empty/null or have been returned by a COPP C ABI
 * function. Passing arbitrary pointers or modified capacity fields is invalid.
 */
void copp_vec_usize_free(struct CoppVecUsize vec);

/**
 * Release a library-owned `f64` matrix returned by COPP.
 *
 * \warning Safety
 * `matrix` must either be empty/null or have been returned by a COPP C ABI
 * function. Passing arbitrary pointers or modified capacity fields is invalid.
 */
void copp_matrix_f64_free(struct CoppMatrixF64 matrix);

/**
 * Forward declaration for third-order profiles returned by TOPP3/COPP3 solvers.
 *
 * Include copp/formulation.h for the full definition and
 * copp_profile_3rd_free.
 */
struct CoppProfile3rd;

/**
 * Extract a second-order COPP profile from a Clarabel primal solution.
 *
 * Use this helper with an expert SOCP result when the raw primal `x` vector
 * should be converted back into the accepted `a(s) = dot{s}^2` profile. The
 * output has length `s_len`; missing tail values are filled with zero and all
 * entries are clamped to be non-negative.
 *
 * \warning Safety
 * `x.data` must be valid for `x.len` reads when `x.len` is non-zero.
 * `out_a` must be valid for one `CoppVecF64` write and must later be
 * released with `copp_vec_f64_free`.
 */
enum CoppStatus copp_clarabel_solution_to_profile_2nd(size_t s_len,
                                                      struct CoppSliceF64 x,
                                                      struct CoppVecF64 *out_a);

/**
 * Extract a third-order COPP profile from a Clarabel primal solution.
 *
 * Use this helper with a TOPP3/COPP3 expert SOCP result when the raw primal
 * `x` vector should be converted back into the accepted
 * `(a, b, num_stationary)` profile. The station vector `s` defines the profile
 * length and interval spacing.
 *
 * \warning Safety
 * `s.data` and `x.data` must be valid for their declared lengths when those
 * lengths are non-zero. `out_profile` must be valid for one `CoppProfile3rd`
 * write and must later be released with `copp_profile_3rd_free`.
 */
enum CoppStatus copp_clarabel_solution_to_profile_3rd(struct CoppSliceF64 s,
                                                      struct CoppSliceF64 x,
                                                      size_t num_stationary_start,
                                                      size_t num_stationary_end,
                                                      struct CoppProfile3rd *out_profile);

/** @} */

#ifdef __cplusplus
}
#endif

#endif /* COPP_CORE_H */
