#ifndef COPP_FORMULATION_H
#define COPP_FORMULATION_H

/*
 * Generated by bindings/c/scripts/generate_headers.ps1.
 * Do not edit by hand; update src/ffi/c and regenerate.
 */

/**
 * \file formulation.h
 * \brief TOPP/COPP problem descriptors, objectives, and profile ownership.
 * \ingroup copp_formulation
 */

#include <stddef.h>
#include "copp/core.h"
#include "copp/robot.h"

#ifdef __cplusplus
extern "C" {
#endif

/**
 * \addtogroup copp_formulation
 * @{
 */

/**
 * COPP objective descriptor kind shared by second- and third-order solvers.
 */
typedef enum CoppObjectiveKind {
    /**
     * Time objective: `weight * integral dt`.
     */
    COPP_OBJECTIVE_KIND_TIME = 0,
    /**
     * Linear objective over solver-specific profile variables.
     *
     * For COPP2, `alpha` is node-based over `a` and `beta` is interval-based
     * over second-order `b`.
     * For COPP3, both `alpha` and `beta` are node-based over third-order
     * `a` and `b`.
     */
    COPP_OBJECTIVE_KIND_LINEAR = 1,
    /**
     * Thermal-energy objective.
     */
    COPP_OBJECTIVE_KIND_THERMAL_ENERGY = 2,
    /**
     * Total-variation torque objective.
     */
    COPP_OBJECTIVE_KIND_TOTAL_VARIATION_TORQUE = 3,
} CoppObjectiveKind;

/**
 * Borrowed objective descriptor for COPP solvers.
 *
 * For `Time`, only `weight` is used.
 * For `Linear`, `alpha` and `beta` are interpreted by each solver family:
 * COPP2 uses node-based `alpha` and interval-based `beta`, while COPP3 uses
 * node-based `alpha` and node-based `beta`.
 * For `ThermalEnergy` and `TotalVariationTorque`, `normalize` must have
 * length equal to the robot dimension. Torque is evaluated through the robot's
 * stored inverse-dynamics callback when provided, otherwise by the default
 * point model (`tau = ddq`).
 */
typedef struct CoppObjective {
    /**
     * Objective kind.
     */
    enum CoppObjectiveKind kind;
    /**
     * Objective weight.
     */
    double weight;
    /**
     * Linear objective coefficient for variable `a`.
     */
    struct CoppSliceF64 alpha;
    /**
     * Linear objective coefficient for variable `b`.
     */
    struct CoppSliceF64 beta;
    /**
     * Torque objective normalization vector.
     */
    struct CoppSliceF64 normalize;
} CoppObjective;

/**
 * Borrowed value descriptor for a COPP2 problem solved from C.
 *
 * This is not an owning handle. `robot` and `objectives` are borrowed only
 * during the solver call, and the solver does not store those pointers after
 * the call returns.
 */
typedef struct Copp2Problem {
    /**
     * Robot handle that owns the station-indexed constraint storage.
     */
    const struct CoppRobot *robot;
    /**
     * Closed start station index.
     */
    size_t idx_s_start;
    /**
     * Closed final station index.
     */
    size_t idx_s_final;
    /**
     * Boundary value `a(idx_s_start) = (ds/dt)^2`.
     */
    double a_start;
    /**
     * Boundary value `a(idx_s_final) = (ds/dt)^2`.
     */
    double a_final;
    /**
     * Objective descriptor array.
     */
    const struct CoppObjective *objectives;
    /**
     * Number of objective descriptors.
     */
    size_t num_objectives;
} Copp2Problem;

/**
 * Borrowed value descriptor for a TOPP2 problem solved from C.
 *
 * This is not an owning handle.  `robot` is borrowed only during TOPP2
 * solver calls such as `topp2_ra` and `copp_reach_set2_*`, and no pointer is
 * stored after the call returns.
 *
 * Refactor it after the C solver flow is validated.
 */
typedef struct Topp2Problem {
    /**
     * Robot handle that owns the station-indexed constraint storage.
     */
    const struct CoppRobot *robot;
    /**
     * Closed start station index.
     */
    size_t idx_s_start;
    /**
     * Closed final station index.
     */
    size_t idx_s_final;
    /**
     * Boundary value `a(idx_s_start) = (ds/dt)^2`.
     */
    double a_start;
    /**
     * Boundary value `a(idx_s_final) = (ds/dt)^2`.
     */
    double a_final;
} Topp2Problem;

/**
 * Owned third-order profile returned by TOPP3/COPP3 C ABI solvers.
 *
 * `a[k]` stores `dot{s}_k^2`, `b[k]` stores `ddot{s}_k`, and
 * `num_stationary_*` stores the effective stationary head/tail interval
 * counts returned by the solver.  Both vectors are library-owned and must be
 * released together with `copp_profile_3rd_free`.
 */
typedef struct CoppProfile3rd {
    /**
     * Node-based profile `a[k] = dot{s}_k^2`.
     */
    struct CoppVecF64 a;
    /**
     * Node-based profile `b[k] = ddot{s}_k`.
     */
    struct CoppVecF64 b;
    /**
     * Effective stationary interval count at the start.
     */
    size_t num_stationary_start;
    /**
     * Effective stationary interval count at the end.
     */
    size_t num_stationary_end;
} CoppProfile3rd;

/**
 * Release a third-order profile returned by COPP.
 *
 * \warning Safety
 * `profile` must either be empty/null or have been returned by a successful
 * third-order C ABI solver call.  Passing arbitrary pointers or modified
 * capacity fields is invalid.
 */
void copp_profile_3rd_free(struct CoppProfile3rd profile);

/**
 * Borrowed value descriptor for a TOPP3 problem solved from C.
 *
 * This is not an owning handle. `robot` and `a_linearization` are borrowed
 * only during the solver call.  Building the internal TOPP3 problem mutates the
 * robot's internal linearized third-order constraint cache.
 */
typedef struct Topp3Problem {
    /**
     * Mutable robot handle that owns station-indexed constraint storage.
     */
    struct CoppRobot *robot;
    /**
     * Start station index. The final index is derived from
     * `a_linearization.len - 1`.
     */
    size_t idx_s_start;
    /**
     * Reference profile `a[k]` used to linearize third-order constraints.
     */
    struct CoppSliceF64 a_linearization;
    /**
     * Boundary value `a(idx_s_start) = dot{s}^2`.
     */
    double a_start;
    /**
     * Boundary value `a(idx_s_final) = dot{s}^2`.
     */
    double a_final;
    /**
     * Boundary value `b(idx_s_start) = ddot{s}`.
     */
    double b_start;
    /**
     * Boundary value `b(idx_s_final) = ddot{s}`.
     */
    double b_final;
    /**
     * User-input stationary upper bound at the start.
     */
    size_t num_stationary_max_start;
    /**
     * User-input stationary upper bound at the end.
     */
    size_t num_stationary_max_end;
    /**
     * Denominator floor used when linearizing third-order constraints.
     */
    double a_linearization_floor;
} Topp3Problem;

/**
 * Borrowed value descriptor for a COPP3 problem solved from C.
 *
 * This extends `Topp3Problem` with borrowed objective descriptors.  It is
 * not an owning handle; all pointers are used only during the solver call.
 */
typedef struct Copp3Problem {
    /**
     * Mutable robot handle that owns station-indexed constraint storage.
     */
    struct CoppRobot *robot;
    /**
     * Start station index. The final index is derived from
     * `a_linearization.len - 1`.
     */
    size_t idx_s_start;
    /**
     * Reference profile `a[k]` used to linearize third-order constraints.
     */
    struct CoppSliceF64 a_linearization;
    /**
     * Boundary value `a(idx_s_start) = dot{s}^2`.
     */
    double a_start;
    /**
     * Boundary value `a(idx_s_final) = dot{s}^2`.
     */
    double a_final;
    /**
     * Boundary value `b(idx_s_start) = ddot{s}`.
     */
    double b_start;
    /**
     * Boundary value `b(idx_s_final) = ddot{s}`.
     */
    double b_final;
    /**
     * User-input stationary upper bound at the start.
     */
    size_t num_stationary_max_start;
    /**
     * User-input stationary upper bound at the end.
     */
    size_t num_stationary_max_end;
    /**
     * Denominator floor used when linearizing third-order constraints.
     */
    double a_linearization_floor;
    /**
     * Objective descriptor array.
     */
    const struct CoppObjective *objectives;
    /**
     * Number of objective descriptors.
     */
    size_t num_objectives;
} Copp3Problem;

/** @} */

#ifdef __cplusplus
}
#endif

#endif /* COPP_FORMULATION_H */
