#ifndef COPP_PATH_H
#define COPP_PATH_H

/*
 * Generated by bindings/c/scripts/generate_headers.ps1.
 * Do not edit by hand; update src/ffi/c and regenerate.
 */

/**
 * \file path.h
 * \brief Path construction, metadata, evaluation, and callback path APIs.
 * \ingroup copp_path
 */

#include <stddef.h>
#include "copp/core.h"

#ifdef __cplusplus
extern "C" {
#endif

/**
 * \addtogroup copp_path
 * @{
 */

/**
 * Opaque C handle for a library-owned `Path`.
 *
 * Create with `copp_path_from_waypoints`, `copp_path_from_evaluator_2nd`, or
 * `copp_path_from_evaluator_3rd` and release exactly once with
 * `copp_path_free`. C callers must not inspect or allocate this type directly.
 */
typedef struct CoppPath CoppPath;

/**
 * C ABI path out-of-range behavior.
 */
typedef enum CoppPathOutOfRangeMode {
    /**
     * Return an error when a query parameter is outside `[s_min, s_max]`.
     */
    COPP_PATH_OUT_OF_RANGE_MODE_ERROR = 0,
    /**
     * Clamp query parameters into `[s_min, s_max]`.
     */
    COPP_PATH_OUT_OF_RANGE_MODE_CLAMP = 1,
} CoppPathOutOfRangeMode;

/**
 * C ABI waypoint-spline parametrization.
 */
typedef enum CoppPathParametrization {
    /**
     * Uniform parameter spacing between waypoints.
     */
    COPP_PATH_PARAMETRIZATION_UNIFORM = 0,
} CoppPathParametrization;

/**
 * Options for waypoint spline path construction.
 *
 * `start_state` and `end_state` are optional matrix views of shape
 * `dim x ((order - 1) / 2)`. Use an empty matrix view (`data = NULL`,
 * `rows = cols = 0`), such as `COPP_MATRIX_VIEW_F64_COLUMN_MAJOR(NULL, 0, 0)`
 * from C, for zero boundary derivatives.
 */
typedef struct CoppPathOptions {
    /**
     * Spline order. Must be odd and at least 3. Common values are 3, 5, and 7.
     */
    size_t order;
    /**
     * Lower bound of the path parameter range.
     */
    double s_min;
    /**
     * Upper bound of the path parameter range.
     */
    double s_max;
    /**
     * Behavior for out-of-range path evaluation.
     */
    enum CoppPathOutOfRangeMode out_of_range_mode;
    /**
     * Waypoint parametrization mode.
     */
    enum CoppPathParametrization parametrization;
    /**
     * Boundary derivatives at `s_min`, or empty for zero boundary derivatives.
     */
    struct CoppMatrixViewF64 start_state;
    /**
     * Boundary derivatives at `s_max`, or empty for zero boundary derivatives.
     */
    struct CoppMatrixViewF64 end_state;
} CoppPathOptions;

/**
 * C callback for evaluating `q`, `dq`, and `ddq`.
 *
 * The callback receives `n` path samples in `s` and must write column-major
 * `dim x n` matrices into `q`, `dq`, and `ddq`.
 */
typedef enum CoppStatus (*CoppPathEvaluate2ndFn)(void *user_data,
                                                 size_t dim,
                                                 size_t n,
                                                 const double *s,
                                                 double *q,
                                                 double *dq,
                                                 double *ddq);

/**
 * C callback for evaluating `q`, `dq`, `ddq`, and `dddq`.
 *
 * The callback receives `n` path samples in `s` and must write column-major
 * `dim x n` matrices into `q`, `dq`, `ddq`, and `dddq`.
 */
typedef enum CoppStatus (*CoppPathEvaluate3rdFn)(void *user_data,
                                                 size_t dim,
                                                 size_t n,
                                                 const double *s,
                                                 double *q,
                                                 double *dq,
                                                 double *ddq,
                                                 double *dddq);

/**
 * Write default waypoint spline options into `out_options`.
 *
 * Defaults are quintic order 5, uniform parametrization, zero boundary
 * derivatives, and out-of-range errors.
 *
 * \warning Safety
 * `out_options` must be valid for one `CoppPathOptions` write.
 */
enum CoppStatus copp_path_default_options(double s_min,
                                          double s_max,
                                          struct CoppPathOptions *out_options);

/**
 * Build a waypoint spline path.
 *
 * `waypoints` must be a matrix view of shape `dim x n_points`, where each
 * column is one waypoint. `options.start_state` and `options.end_state` may be
 * empty to use zero boundary derivatives.
 *
 * Column-major input with `leading_dim >= rows` avoids a temporary layout
 * copy while building the spline coefficients. Row-major input is accepted
 * and copied once into column-major temporary storage. Spline construction
 * still allocates library-owned polynomial coefficients for the returned path.
 *
 * On success, `*out_path` receives a non-null handle that must be released
 * with `copp_path_free`.
 *
 * \warning Safety
 * Non-empty matrix views in `waypoints` and `options` must point to valid
 * `double` arrays for their declared layouts for the duration of this call.
 * `out_path` must be valid for one `CoppPath*` write.
 */
enum CoppStatus copp_path_from_waypoints(struct CoppMatrixViewF64 waypoints,
                                         struct CoppPathOptions options,
                                         struct CoppPath **out_path);

/**
 * Build a path from a C callback that provides derivatives up to 2nd order.
 *
 * The callback operates on a batch of `n` path samples and must write
 * column-major `dim x n` output matrices (`data[row + col * dim]`) for `q`,
 * `dq`, and `ddq`. The resulting path can be evaluated or sampled up to 2nd
 * order. Third-order evaluation returns
 * `COPP_STATUS_PATH_UNSUPPORTED_DERIVATIVE_ORDER`.
 *
 * The callback pointer and `user_data` are borrowed by the created path and
 * must remain valid until `copp_path_free` is called. Calls into the callback
 * are serialized per path handle.
 *
 * On success, `*out_path` receives a non-null handle that must be released
 * with `copp_path_free`.
 *
 * \warning Safety
 * `evaluate_2nd` must be non-null and valid until `copp_path_free`.
 * `user_data` must remain valid for all callback calls. `out_path` must be
 * valid for one `CoppPath*` write.
 */
enum CoppStatus copp_path_from_evaluator_2nd(size_t dim,
                                             double s_min,
                                             double s_max,
                                             CoppPathEvaluate2ndFn evaluate_2nd,
                                             void *user_data,
                                             struct CoppPath **out_path);

/**
 * Build a path from C callbacks that provide derivatives up to 3rd order.
 *
 * `evaluate_3rd` is required. `evaluate_2nd` may be null; when it is null,
 * second-order evaluation calls `evaluate_3rd` internally and discards `dddq`.
 * Both callbacks operate on a batch of `n` path samples and must write
 * column-major `dim x n` output matrices (`data[row + col * dim]`).
 *
 * The callback pointers and `user_data` are borrowed by the created path and
 * must remain valid until `copp_path_free` is called. Calls into the callbacks
 * are serialized per path handle.
 *
 * On success, `*out_path` receives a non-null handle that must be released
 * with `copp_path_free`.
 *
 * \warning Safety
 * `evaluate_3rd` must be non-null and valid until `copp_path_free`.
 * `evaluate_2nd`, when non-null, must follow the same lifetime rule.
 * `user_data` must remain valid for all callback calls. `out_path` must be
 * valid for one `CoppPath*` write.
 */
enum CoppStatus copp_path_from_evaluator_3rd(size_t dim,
                                             double s_min,
                                             double s_max,
                                             CoppPathEvaluate2ndFn evaluate_2nd,
                                             CoppPathEvaluate3rdFn evaluate_3rd,
                                             void *user_data,
                                             struct CoppPath **out_path);

/**
 * Return the path dimension.
 *
 * \warning Safety
 * `path` must be a non-null handle created by this module.
 * `out_dim` must be valid for one `size_t` write.
 */
enum CoppStatus copp_path_dim(const struct CoppPath *path, size_t *out_dim);

/**
 * Return the valid path parameter range.
 *
 * \warning Safety
 * `path` must be a non-null handle created by this module.
 * `out_s_min` and `out_s_max` must be valid for one `double` write each.
 */
enum CoppStatus copp_path_s_range(const struct CoppPath *path,
                                  double *out_s_min,
                                  double *out_s_max);

/**
 * Evaluate `q`, `dq`, and `ddq` at the supplied path parameters.
 *
 * Output matrices are column-major with shape `dim x s.len` and must be
 * released with `copp_matrix_f64_free`.
 *
 * \warning Safety
 * `path` must be a non-null handle created by this module.
 * `s.data` must be valid for `s.len` reads when non-empty. Output pointers
 * must be valid for one `CoppMatrixF64` write each.
 */
enum CoppStatus copp_path_evaluate_up_to_2nd(const struct CoppPath *path,
                                             struct CoppSliceF64 s,
                                             struct CoppMatrixF64 *out_q,
                                             struct CoppMatrixF64 *out_dq,
                                             struct CoppMatrixF64 *out_ddq);

/**
 * Evaluate `q`, `dq`, `ddq`, and `dddq` at the supplied path parameters.
 *
 * Output matrices are column-major with shape `dim x s.len` and must be
 * released with `copp_matrix_f64_free`.
 *
 * \warning Safety
 * `path` must be a non-null handle created by this module.
 * `s.data` must be valid for `s.len` reads when non-empty. Output pointers
 * must be valid for one `CoppMatrixF64` write each.
 */
enum CoppStatus copp_path_evaluate_up_to_3rd(const struct CoppPath *path,
                                             struct CoppSliceF64 s,
                                             struct CoppMatrixF64 *out_q,
                                             struct CoppMatrixF64 *out_dq,
                                             struct CoppMatrixF64 *out_ddq,
                                             struct CoppMatrixF64 *out_dddq);

/**
 * Release a path handle created by this module.
 *
 * Passing null is allowed and has no effect.
 *
 * \warning Safety
 * `path` must either be null or a live path handle that has not already been
 * freed.
 */
void copp_path_free(struct CoppPath *path);

/** @} */

#ifdef __cplusplus
}
#endif

#endif /* COPP_PATH_H */
