#ifndef COPP_TOPP3_H
#define COPP_TOPP3_H

/*
 * Generated by bindings/c/scripts/generate_headers.ps1.
 * Do not edit by hand; update src/ffi/c and regenerate.
 */

/**
 * \file topp3.h
 * \brief TOPP3-LP and TOPP3-SOCP APIs.
 * \ingroup copp_topp3
 */

#include <stddef.h>
#include "copp/core.h"
#include "copp/formulation.h"

#ifdef __cplusplus
extern "C" {
#endif

/**
 * \addtogroup copp_topp3
 * @{
 */

/**
 * Forward declaration for expert TOPP3-SOCP diagnostics.
 *
 * Include copp/copp3.h when the full Copp3SocpResult definition or
 * copp3_socp_result_free is needed.
 */
typedef struct Copp3SocpResult Copp3SocpResult;

/**
 * Solve a TOPP3-LP problem.
 *
 * This C ABI builds an internal TOPP3 problem from the borrowed `Topp3Problem`,
 * forwards `options` to the Clarabel backend, and returns only the accepted
 * third-order profile.
 *
 * On success, `out_profile` owns COPP-allocated `a` and `b` vectors and must
 * be released with `copp_profile_3rd_free`.
 *
 * \warning Safety
 * `problem.robot` must be a non-null mutable handle returned by
 * `copp_robot_create` and must remain valid for the duration of this call.
 * The solver builds the internal problem by linearizing third-order constraints,
 * which mutates the robot's internal constraint cache. `out_profile` must be
 * valid for one `CoppProfile3rd` write.
 */
enum CoppStatus topp3_lp(struct Topp3Problem problem,
                         struct CoppClarabelOptions options,
                         struct CoppProfile3rd *out_profile);

/**
 * Solve a TOPP3-LP problem and always return Clarabel diagnostics.
 *
 * This expert entry mirrors `topp3_lp_expert`: true runtime failures
 * still return a non-OK `CoppStatus`, but non-accepted Clarabel statuses are
 * reported inside `out_result` with `has_profile == false` and the function
 * returns `COPP_STATUS_OK`.
 *
 * TOPP3-LP has no user-provided COPP objective list, so
 * `out_result.objective_value` is NaN and `out_result.objective_terms` is an
 * empty vector. Raw Clarabel objective values and solver diagnostics are still
 * populated.
 *
 * \warning Safety
 * Same safety requirements as `topp3_lp`. `out_result` must be valid for one
 * `Copp3SocpResult` write and must later be released with
 * `copp3_socp_result_free`.
 */
enum CoppStatus topp3_lp_expert(struct Topp3Problem problem,
                                struct CoppClarabelOptions options,
                                struct Copp3SocpResult *out_result);

/**
 * Solve a TOPP3-SOCP problem.
 *
 * This C ABI builds an internal TOPP3 problem from the borrowed `Topp3Problem`,
 * forwards `options` to the Clarabel backend, and returns only the accepted
 * third-order profile.
 *
 * On success, `out_profile` owns COPP-allocated `a` and `b` vectors and must
 * be released with `copp_profile_3rd_free`.
 *
 * \warning Safety
 * `problem.robot` must be a non-null mutable handle returned by
 * `copp_robot_create` and must remain valid for the duration of this call.
 * The solver builds the internal problem by linearizing third-order constraints,
 * which mutates the robot's internal constraint cache. `out_profile` must be
 * valid for one `CoppProfile3rd` write.
 */
enum CoppStatus topp3_socp(struct Topp3Problem problem,
                           struct CoppClarabelOptions options,
                           struct CoppProfile3rd *out_profile);

/**
 * Solve a TOPP3-SOCP problem and always return Clarabel diagnostics.
 *
 * This expert entry mirrors `topp3_socp_expert`: true runtime failures
 * still return a non-OK `CoppStatus`, but non-accepted Clarabel statuses are
 * reported inside `out_result` with `has_profile == false` and the function
 * returns `COPP_STATUS_OK`.
 *
 * TOPP3-SOCP has no user-provided COPP objective list, so
 * `out_result.objective_value` is NaN and `out_result.objective_terms` is an
 * empty vector. Raw Clarabel objective values and solver diagnostics are still
 * populated.
 *
 * \warning Safety
 * Same safety requirements as `topp3_socp`. `out_result` must be valid for
 * one `Copp3SocpResult` write and must later be released with
 * `copp3_socp_result_free`.
 */
enum CoppStatus topp3_socp_expert(struct Topp3Problem problem,
                                  struct CoppClarabelOptions options,
                                  struct Copp3SocpResult *out_result);

/** @} */

#ifdef __cplusplus
}
#endif

#endif /* COPP_TOPP3_H */
