#ifndef COPP_TOPP2_H
#define COPP_TOPP2_H

/*
 * Generated by bindings/c/scripts/generate_headers.ps1.
 * Do not edit by hand; update src/ffi/c and regenerate.
 */

/**
 * \file topp2.h
 * \brief TOPP2-RA and second-order reachable-set APIs.
 * \ingroup copp_topp2
 */

#include <stddef.h>
#include "copp/core.h"
#include "copp/formulation.h"

#ifdef __cplusplus
extern "C" {
#endif

/**
 * \addtogroup copp_topp2
 * @{
 */

/**
 * Options for TOPP2-RA reachability analysis.
 */
typedef struct Topp2RaOptions {
    /**
     * Feasibility tolerance used by LP subproblems.
     */
    double lp_feas_tol;
    /**
     * Absolute tolerance for comparing interval bounds.
     */
    double a_cmp_abs_tol;
    /**
     * Relative tolerance for comparing interval bounds.
     */
    double a_cmp_rel_tol;
    /**
     * Verbosity level for diagnostics.
     */
    enum CoppVerbosity verbosity;
} Topp2RaOptions;

/**
 * Write default TOPP2-RA options into `out_options`.
 *
 * \warning Safety
 * `out_options` must be valid for one `Topp2RaOptions` write.
 */
enum CoppStatus topp2_ra_default_options(struct Topp2RaOptions *out_options);

/**
 * Solve a TOPP2-RA problem.
 *
 * On success, `out_a` owns a COPP-allocated vector containing the solved
 * `a(s) = (ds/dt)^2` profile over the closed station interval and must be
 * released with `copp_vec_f64_free`.
 *
 * \warning Safety
 * `problem.robot` must be a non-null handle returned by `copp_robot_create`
 * and must remain valid for the duration of this call.  The robot must not be
 * freed or mutated concurrently during the solve.  `out_a` must be valid for
 * one `CoppVecF64` write.
 */
enum CoppStatus topp2_ra(struct Topp2Problem problem,
                         struct Topp2RaOptions options,
                         struct CoppVecF64 *out_a);

/**
 * Reachable intervals returned by TOPP2 reachable-set construction.
 *
 * For each station, the feasible interval is `a_min[k] <= a[k] <= a_max[k]`
 * where `a = (ds/dt)^2`.  The field order is `a_max` first, then `a_min`.
 * Both vectors are library-owned and must
 * be released together with `copp_reach_set2_result_free`.
 */
typedef struct CoppReachSet2Result {
    /**
     * Upper reachable bound for each station.
     */
    struct CoppVecF64 a_max;
    /**
     * Lower reachable bound for each station.
     */
    struct CoppVecF64 a_min;
} CoppReachSet2Result;

/**
 * Compute backward-only TOPP2 reachable intervals.
 *
 * This performs the same backward pass as `reach_set2_backward`: the
 * terminal boundary `a_final` is enforced, while the start boundary is only
 * checked for basic feasibility and is not imposed by a forward clipping pass.
 *
 * On success, `out_result` owns two vectors with length
 * `idx_s_final - idx_s_start + 1`, ordered as `a_max` then `a_min`.  Release
 * them with `copp_reach_set2_result_free`.
 *
 * \warning Safety
 * `problem.robot` must be a non-null handle returned by `copp_robot_create`
 * and must remain valid for the duration of this call.  The robot must not be
 * freed or mutated concurrently.  `out_result` must be valid for one
 * `CoppReachSet2Result` write.
 */
enum CoppStatus copp_reach_set2_backward(struct Topp2Problem problem,
                                         struct Topp2RaOptions options,
                                         struct CoppReachSet2Result *out_result);

/**
 * Compute bidirectional TOPP2 reachable intervals.
 *
 * This performs a backward pass followed by a forward clipping pass, enforcing
 * both boundary values `a_start` and `a_final`.
 *
 * On success, `out_result` owns two vectors with length
 * `idx_s_final - idx_s_start + 1`, ordered as `a_max` then `a_min`.  Release
 * them with `copp_reach_set2_result_free`.
 *
 * \warning Safety
 * `problem.robot` must be a non-null handle returned by `copp_robot_create`
 * and must remain valid for the duration of this call.  The robot must not be
 * freed or mutated concurrently.  `out_result` must be valid for one
 * `CoppReachSet2Result` write.
 */
enum CoppStatus copp_reach_set2_bidirectional(struct Topp2Problem problem,
                                              struct Topp2RaOptions options,
                                              struct CoppReachSet2Result *out_result);

/**
 * Release a reachable-set result returned by COPP.
 *
 * \warning Safety
 * `result` must either be empty/null or have been returned by a successful
 * `copp_reach_set2_backward` / `copp_reach_set2_bidirectional` call.  Passing
 * arbitrary pointers or modified capacity fields is invalid.
 */
void copp_reach_set2_result_free(struct CoppReachSet2Result result);

/** @} */

#ifdef __cplusplus
}
#endif

#endif /* COPP_TOPP2_H */
